name: manga-reader
services:
  manga-reader:
    image: ghcr.io/tonycrane/manga-reader:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      COOKIE_SECURE: "false"
    volumes:
      - /path/to/manga:/manga:ro
      - ./.data:/data
      - ./.processed:/processed
